spring.application.name=ms-digitalfix-bff

# Configuración del puerto del servidor
server.port=8080

# Configuración de seguridad para validación de JWT (Azure AD / Entra ID)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://login.microsoftonline.com/2ff9414f-7d61-4bd8-919b-be3438b82d0d/v2.0}
spring.security.oauth2.resourceserver.jwt.audiences=8ab1f6e4-28f9-46e0-8981-2e8bd3c0e868,api://8ab1f6e4-28f9-46e0-8981-2e8bd3c0e868

logging.level.org.springframework.security=TRACE
