spring.application.name=ms-digitalfix-bff

# Configuración del puerto del servidor
server.port=8080

# Configuración de seguridad para validación de JWT (Azure AD)
#aca va el tenantid
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/<TENANT_ID>/v2.0
#aca va el api clientid
spring.security.oauth2.resourceserver.jwt.audiences=api://<API_CLIENT_ID>
