server.port=8082

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/catalog_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://login.microsoftonline.com/2ff9414f-7d61-4bd8-919b-be3438b82d0d/v2.0}
spring.security.oauth2.resourceserver.jwt.audiences=8ab1f6e4-28f9-46e0-8981-2e8bd3c0e868,api://8ab1f6e4-28f9-46e0-8981-2e8bd3c0e868
